### ISSUE TITLE
add an item to an order

### ISSUE THREAD

**Issue by TheAriaki** [CSCI-GA-2820-SP24-003/orders#17]
**As a** customer
**I need** a function that allows me to add an item to my order  
**So that** I can add additional products to my order when needed 
   
 ### Details and Assumptions
 * Up to a specific processing step, the system permits products to be added to an order; after that point, no additional additions are permitted.
The product ID, quantity, and any special preferences or adjustments that the client may have requested must all be included with each item that is added to an order.
When new things are added, the system needs to instantly update the order total and item count.
POST  /orders/{id}/items <- add an item to an order

## Acceptance Criteria
```gherkin
 - [ ] **Scenario: Add item to order**
  - Given a user is logged in and has an open order
  - When the user adds a new item to the order with a valid product ID, quantity, and preferences
  - Then the system should update the order total and item count immediately and the user should see the new item in their order
- [ ] **Scenario: Add item to order after processing step**
  - Given a user is logged in and has an open order
  - When the user tries to add a new item to the order after the processing step
  - Then the system should not allow the addition of the item and the user should see an error message explaining that additions are not permitted after the processing step
 ```

**Comment by IhwaHussain** [comment]
What is the specific reasoning behind not allowing the user to add items after a specific processing step? Is it to assure serializability or some other specific purpose?

**Comment by TheAriaki** [comment]
My thought is after the order is checked out, the customer should not be able to add more items.

**Comment by bhavna-matwani** [comment]
Let's update that in the description as well, making what processing step is a little more clear
