### ISSUE TITLE
Set Up Selenium

### ISSUE THREAD

**Issue by IhwaHussain** [CSCI-GA-2820-SP24-003/orders#64]
**As a** developer,

**I need** the ability to use selenium,

**So that** I can utilize BDD testing for orders microservice feautures

## Details and Assumptions

- Change the Dockerfile to use selenium
- Create a `.github/workflows/bdd.yml` file and configure GitHub
Actions to run test cases every time someone pushes to the master
branch or submits a Pull Request.
- Have a `features` folder that contains
  -  `environment.py` file that setups BDD testing on chrome/firefox
  -  `steps/order_steps.py` file that deletes orders from previous tests, and loads in new ones

## Acceptance Criteria

```gherkin
Given a developer who has prepared a github branch
When the developer makes a pull request to main for that branch
Then an action should run to make BDD/Selenium tests run and report results of the pull request

TBD
```

**Comment by bhavna-matwani** [comment]
Shouldn't we add steps/order_steps.py after adding feature files?

**Comment by bhavna-matwani** [comment]
Shouldn't we add steps/order_steps.py after adding feature files?
