### ISSUE TITLE
Update order

### ISSUE THREAD

**Issue by bhavna-matwani** [CSCI-GA-2820-SP24-003/orders#8]
**As an** Order Manager
**I need** I can update the order
**So that** if there is a need to adjust details necessary to the delivery of an order, it can be done
   
 ### Details and Assumptions
 * There is a database schema with the required fields, so updating the order should update the fields within the order. 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given order id, field to be updated, and a new field
the fields can be updated
 Then database entry with that order id should be updated
```

**Comment by anishabhatnagar** [comment]
The title appears to suggest that this story pertains to updating individual items within an order, akin to what was addressed in issue #18. However, the acceptance criteria seem to indicate it's related to the `PUT /orders/{id} ` endpoint for updating an entire order. Could you please provide some clarification on this?

**Comment by bhavna-matwani** [comment]
I updated the description

**Comment by anishabhatnagar** [comment]
With the updated description i believe this and issue #18 "update a single item in an order" are the same. And therefore redundant.
